// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laborator6.Data;

namespace laborator6.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201105171308_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("laborator6.Entities.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Do .NET Homework!",
                            IsDone = false
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Do ML Homework!",
                            IsDone = false
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Do ISSA Homework!",
                            IsDone = true
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Do SI Homework!",
                            IsDone = false
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Do Python Homework!",
                            IsDone = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
